import { PrismaClient } from "@prisma/client";
import bcrypt from "bcryptjs";

const prisma = new PrismaClient();

const nationalities = [
  { code: "AF", code3: "AFG", name: "Afghanistan", flagEmoji: "🇦🇫", region: "Asia" },
  { code: "AL", code3: "ALB", name: "Albania", flagEmoji: "🇦🇱", region: "Europe" },
  { code: "DZ", code3: "DZA", name: "Algeria", flagEmoji: "🇩🇿", region: "Africa" },
  { code: "AD", code3: "AND", name: "Andorra", flagEmoji: "🇦🇩", region: "Europe" },
  { code: "AO", code3: "AGO", name: "Angola", flagEmoji: "🇦🇴", region: "Africa" },
  { code: "AR", code3: "ARG", name: "Argentina", flagEmoji: "🇦🇷", region: "Americas" },
  { code: "AM", code3: "ARM", name: "Armenia", flagEmoji: "🇦🇲", region: "Asia" },
  { code: "AU", code3: "AUS", name: "Australia", flagEmoji: "🇦🇺", region: "Oceania" },
  { code: "AT", code3: "AUT", name: "Austria", flagEmoji: "🇦🇹", region: "Europe" },
  { code: "AZ", code3: "AZE", name: "Azerbaijan", flagEmoji: "🇦🇿", region: "Asia" },
  { code: "BS", code3: "BHS", name: "Bahamas", flagEmoji: "🇧🇸", region: "Americas" },
  { code: "BH", code3: "BHR", name: "Bahrain", flagEmoji: "🇧🇭", region: "Asia" },
  { code: "BD", code3: "BGD", name: "Bangladesh", flagEmoji: "🇧🇩", region: "Asia" },
  { code: "BY", code3: "BLR", name: "Belarus", flagEmoji: "🇧🇾", region: "Europe" },
  { code: "BE", code3: "BEL", name: "Belgium", flagEmoji: "🇧🇪", region: "Europe" },
  { code: "BZ", code3: "BLZ", name: "Belize", flagEmoji: "🇧🇿", region: "Americas" },
  { code: "BJ", code3: "BEN", name: "Benin", flagEmoji: "🇧🇯", region: "Africa" },
  { code: "BT", code3: "BTN", name: "Bhutan", flagEmoji: "🇧🇹", region: "Asia" },
  { code: "BO", code3: "BOL", name: "Bolivia", flagEmoji: "🇧🇴", region: "Americas" },
  { code: "BA", code3: "BIH", name: "Bosnia and Herzegovina", flagEmoji: "🇧🇦", region: "Europe" },
  { code: "BW", code3: "BWA", name: "Botswana", flagEmoji: "🇧🇼", region: "Africa" },
  { code: "BR", code3: "BRA", name: "Brazil", flagEmoji: "🇧🇷", region: "Americas" },
  { code: "BN", code3: "BRN", name: "Brunei", flagEmoji: "🇧🇳", region: "Asia" },
  { code: "BG", code3: "BGR", name: "Bulgaria", flagEmoji: "🇧🇬", region: "Europe" },
  { code: "BF", code3: "BFA", name: "Burkina Faso", flagEmoji: "🇧🇫", region: "Africa" },
  { code: "BI", code3: "BDI", name: "Burundi", flagEmoji: "🇧🇮", region: "Africa" },
  { code: "KH", code3: "KHM", name: "Cambodia", flagEmoji: "🇰🇭", region: "Asia" },
  { code: "CM", code3: "CMR", name: "Cameroon", flagEmoji: "🇨🇲", region: "Africa" },
  { code: "CA", code3: "CAN", name: "Canada", flagEmoji: "🇨🇦", region: "Americas" },
  { code: "CV", code3: "CPV", name: "Cape Verde", flagEmoji: "🇨🇻", region: "Africa" },
  { code: "CF", code3: "CAF", name: "Central African Republic", flagEmoji: "🇨🇫", region: "Africa" },
  { code: "TD", code3: "TCD", name: "Chad", flagEmoji: "🇹🇩", region: "Africa" },
  { code: "CL", code3: "CHL", name: "Chile", flagEmoji: "🇨🇱", region: "Americas" },
  { code: "CN", code3: "CHN", name: "China", flagEmoji: "🇨🇳", region: "Asia" },
  { code: "CO", code3: "COL", name: "Colombia", flagEmoji: "🇨🇴", region: "Americas" },
  { code: "KM", code3: "COM", name: "Comoros", flagEmoji: "🇰🇲", region: "Africa" },
  { code: "CG", code3: "COG", name: "Congo", flagEmoji: "🇨🇬", region: "Africa" },
  { code: "CD", code3: "COD", name: "Congo (DRC)", flagEmoji: "🇨🇩", region: "Africa" },
  { code: "CR", code3: "CRI", name: "Costa Rica", flagEmoji: "🇨🇷", region: "Americas" },
  { code: "HR", code3: "HRV", name: "Croatia", flagEmoji: "🇭🇷", region: "Europe" },
  { code: "CU", code3: "CUB", name: "Cuba", flagEmoji: "🇨🇺", region: "Americas" },
  { code: "CY", code3: "CYP", name: "Cyprus", flagEmoji: "🇨🇾", region: "Europe" },
  { code: "CZ", code3: "CZE", name: "Czech Republic", flagEmoji: "🇨🇿", region: "Europe" },
  { code: "DK", code3: "DNK", name: "Denmark", flagEmoji: "🇩🇰", region: "Europe" },
  { code: "DJ", code3: "DJI", name: "Djibouti", flagEmoji: "🇩🇯", region: "Africa" },
  { code: "DM", code3: "DMA", name: "Dominica", flagEmoji: "🇩🇲", region: "Americas" },
  { code: "DO", code3: "DOM", name: "Dominican Republic", flagEmoji: "🇩🇴", region: "Americas" },
  { code: "EC", code3: "ECU", name: "Ecuador", flagEmoji: "🇪🇨", region: "Americas" },
  { code: "EG", code3: "EGY", name: "Egypt", flagEmoji: "🇪🇬", region: "Africa" },
  { code: "SV", code3: "SLV", name: "El Salvador", flagEmoji: "🇸🇻", region: "Americas" },
  { code: "GQ", code3: "GNQ", name: "Equatorial Guinea", flagEmoji: "🇬🇶", region: "Africa" },
  { code: "ER", code3: "ERI", name: "Eritrea", flagEmoji: "🇪🇷", region: "Africa" },
  { code: "EE", code3: "EST", name: "Estonia", flagEmoji: "🇪🇪", region: "Europe" },
  { code: "ET", code3: "ETH", name: "Ethiopia", flagEmoji: "🇪🇹", region: "Africa" },
  { code: "FJ", code3: "FJI", name: "Fiji", flagEmoji: "🇫🇯", region: "Oceania" },
  { code: "FI", code3: "FIN", name: "Finland", flagEmoji: "🇫🇮", region: "Europe" },
  { code: "FR", code3: "FRA", name: "France", flagEmoji: "🇫🇷", region: "Europe" },
  { code: "GA", code3: "GAB", name: "Gabon", flagEmoji: "🇬🇦", region: "Africa" },
  { code: "GM", code3: "GMB", name: "Gambia", flagEmoji: "🇬🇲", region: "Africa" },
  { code: "GE", code3: "GEO", name: "Georgia", flagEmoji: "🇬🇪", region: "Asia" },
  { code: "DE", code3: "DEU", name: "Germany", flagEmoji: "🇩🇪", region: "Europe" },
  { code: "GH", code3: "GHA", name: "Ghana", flagEmoji: "🇬🇭", region: "Africa" },
  { code: "GR", code3: "GRC", name: "Greece", flagEmoji: "🇬🇷", region: "Europe" },
  { code: "GT", code3: "GTM", name: "Guatemala", flagEmoji: "🇬🇹", region: "Americas" },
  { code: "GN", code3: "GIN", name: "Guinea", flagEmoji: "🇬🇳", region: "Africa" },
  { code: "GW", code3: "GNB", name: "Guinea-Bissau", flagEmoji: "🇬🇼", region: "Africa" },
  { code: "GY", code3: "GUY", name: "Guyana", flagEmoji: "🇬🇾", region: "Americas" },
  { code: "HT", code3: "HTI", name: "Haiti", flagEmoji: "🇭🇹", region: "Americas" },
  { code: "HN", code3: "HND", name: "Honduras", flagEmoji: "🇭🇳", region: "Americas" },
  { code: "HK", code3: "HKG", name: "Hong Kong", flagEmoji: "🇭🇰", region: "Asia" },
  { code: "HU", code3: "HUN", name: "Hungary", flagEmoji: "🇭🇺", region: "Europe" },
  { code: "IS", code3: "ISL", name: "Iceland", flagEmoji: "🇮🇸", region: "Europe" },
  { code: "IN", code3: "IND", name: "India", flagEmoji: "🇮🇳", region: "Asia" },
  { code: "ID", code3: "IDN", name: "Indonesia", flagEmoji: "🇮🇩", region: "Asia" },
  { code: "IR", code3: "IRN", name: "Iran", flagEmoji: "🇮🇷", region: "Asia" },
  { code: "IQ", code3: "IRQ", name: "Iraq", flagEmoji: "🇮🇶", region: "Asia" },
  { code: "IE", code3: "IRL", name: "Ireland", flagEmoji: "🇮🇪", region: "Europe" },
  { code: "IL", code3: "ISR", name: "Israel", flagEmoji: "🇮🇱", region: "Asia" },
  { code: "IT", code3: "ITA", name: "Italy", flagEmoji: "🇮🇹", region: "Europe" },
  { code: "JM", code3: "JAM", name: "Jamaica", flagEmoji: "🇯🇲", region: "Americas" },
  { code: "JP", code3: "JPN", name: "Japan", flagEmoji: "🇯🇵", region: "Asia" },
  { code: "JO", code3: "JOR", name: "Jordan", flagEmoji: "🇯🇴", region: "Asia" },
  { code: "KZ", code3: "KAZ", name: "Kazakhstan", flagEmoji: "🇰🇿", region: "Asia" },
  { code: "KE", code3: "KEN", name: "Kenya", flagEmoji: "🇰🇪", region: "Africa" },
  { code: "KI", code3: "KIR", name: "Kiribati", flagEmoji: "🇰🇮", region: "Oceania" },
  { code: "KP", code3: "PRK", name: "North Korea", flagEmoji: "🇰🇵", region: "Asia" },
  { code: "KR", code3: "KOR", name: "South Korea", flagEmoji: "🇰🇷", region: "Asia" },
  { code: "KW", code3: "KWT", name: "Kuwait", flagEmoji: "🇰🇼", region: "Asia" },
  { code: "KG", code3: "KGZ", name: "Kyrgyzstan", flagEmoji: "🇰🇬", region: "Asia" },
  { code: "LA", code3: "LAO", name: "Laos", flagEmoji: "🇱🇦", region: "Asia" },
  { code: "LV", code3: "LVA", name: "Latvia", flagEmoji: "🇱🇻", region: "Europe" },
  { code: "LB", code3: "LBN", name: "Lebanon", flagEmoji: "🇱🇧", region: "Asia" },
  { code: "LS", code3: "LSO", name: "Lesotho", flagEmoji: "🇱🇸", region: "Africa" },
  { code: "LR", code3: "LBR", name: "Liberia", flagEmoji: "🇱🇷", region: "Africa" },
  { code: "LY", code3: "LBY", name: "Libya", flagEmoji: "🇱🇾", region: "Africa" },
  { code: "LI", code3: "LIE", name: "Liechtenstein", flagEmoji: "🇱🇮", region: "Europe" },
  { code: "LT", code3: "LTU", name: "Lithuania", flagEmoji: "🇱🇹", region: "Europe" },
  { code: "LU", code3: "LUX", name: "Luxembourg", flagEmoji: "🇱🇺", region: "Europe" },
  { code: "MO", code3: "MAC", name: "Macao", flagEmoji: "🇲🇴", region: "Asia" },
  { code: "MG", code3: "MDG", name: "Madagascar", flagEmoji: "🇲🇬", region: "Africa" },
  { code: "MW", code3: "MWI", name: "Malawi", flagEmoji: "🇲🇼", region: "Africa" },
  { code: "MY", code3: "MYS", name: "Malaysia", flagEmoji: "🇲🇾", region: "Asia" },
  { code: "MV", code3: "MDV", name: "Maldives", flagEmoji: "🇲🇻", region: "Asia" },
  { code: "ML", code3: "MLI", name: "Mali", flagEmoji: "🇲🇱", region: "Africa" },
  { code: "MT", code3: "MLT", name: "Malta", flagEmoji: "🇲🇹", region: "Europe" },
  { code: "MH", code3: "MHL", name: "Marshall Islands", flagEmoji: "🇲🇭", region: "Oceania" },
  { code: "MR", code3: "MRT", name: "Mauritania", flagEmoji: "🇲🇷", region: "Africa" },
  { code: "MU", code3: "MUS", name: "Mauritius", flagEmoji: "🇲🇺", region: "Africa" },
  { code: "MX", code3: "MEX", name: "Mexico", flagEmoji: "🇲🇽", region: "Americas" },
  { code: "FM", code3: "FSM", name: "Micronesia", flagEmoji: "🇫🇲", region: "Oceania" },
  { code: "MD", code3: "MDA", name: "Moldova", flagEmoji: "🇲🇩", region: "Europe" },
  { code: "MC", code3: "MCO", name: "Monaco", flagEmoji: "🇲🇨", region: "Europe" },
  { code: "MN", code3: "MNG", name: "Mongolia", flagEmoji: "🇲🇳", region: "Asia" },
  { code: "ME", code3: "MNE", name: "Montenegro", flagEmoji: "🇲🇪", region: "Europe" },
  { code: "MA", code3: "MAR", name: "Morocco", flagEmoji: "🇲🇦", region: "Africa" },
  { code: "MZ", code3: "MOZ", name: "Mozambique", flagEmoji: "🇲🇿", region: "Africa" },
  { code: "MM", code3: "MMR", name: "Myanmar", flagEmoji: "🇲🇲", region: "Asia" },
  { code: "NA", code3: "NAM", name: "Namibia", flagEmoji: "🇳🇦", region: "Africa" },
  { code: "NR", code3: "NRU", name: "Nauru", flagEmoji: "🇳🇷", region: "Oceania" },
  { code: "NP", code3: "NPL", name: "Nepal", flagEmoji: "🇳🇵", region: "Asia" },
  { code: "NL", code3: "NLD", name: "Netherlands", flagEmoji: "🇳🇱", region: "Europe" },
  { code: "NZ", code3: "NZL", name: "New Zealand", flagEmoji: "🇳🇿", region: "Oceania" },
  { code: "NI", code3: "NIC", name: "Nicaragua", flagEmoji: "🇳🇮", region: "Americas" },
  { code: "NE", code3: "NER", name: "Niger", flagEmoji: "🇳🇪", region: "Africa" },
  { code: "NG", code3: "NGA", name: "Nigeria", flagEmoji: "🇳🇬", region: "Africa" },
  { code: "MK", code3: "MKD", name: "North Macedonia", flagEmoji: "🇲🇰", region: "Europe" },
  { code: "NO", code3: "NOR", name: "Norway", flagEmoji: "🇳🇴", region: "Europe" },
  { code: "OM", code3: "OMN", name: "Oman", flagEmoji: "🇴🇲", region: "Asia" },
  { code: "PK", code3: "PAK", name: "Pakistan", flagEmoji: "🇵🇰", region: "Asia" },
  { code: "PW", code3: "PLW", name: "Palau", flagEmoji: "🇵🇼", region: "Oceania" },
  { code: "PA", code3: "PAN", name: "Panama", flagEmoji: "🇵🇦", region: "Americas" },
  { code: "PG", code3: "PNG", name: "Papua New Guinea", flagEmoji: "🇵🇬", region: "Oceania" },
  { code: "PY", code3: "PRY", name: "Paraguay", flagEmoji: "🇵🇾", region: "Americas" },
  { code: "PE", code3: "PER", name: "Peru", flagEmoji: "🇵🇪", region: "Americas" },
  { code: "PH", code3: "PHL", name: "Philippines", flagEmoji: "🇵🇭", region: "Asia" },
  { code: "PL", code3: "POL", name: "Poland", flagEmoji: "🇵🇱", region: "Europe" },
  { code: "PT", code3: "PRT", name: "Portugal", flagEmoji: "🇵🇹", region: "Europe" },
  { code: "QA", code3: "QAT", name: "Qatar", flagEmoji: "🇶🇦", region: "Asia" },
  { code: "RO", code3: "ROU", name: "Romania", flagEmoji: "🇷🇴", region: "Europe" },
  { code: "RU", code3: "RUS", name: "Russia", flagEmoji: "🇷🇺", region: "Europe" },
  { code: "RW", code3: "RWA", name: "Rwanda", flagEmoji: "🇷🇼", region: "Africa" },
  { code: "KN", code3: "KNA", name: "Saint Kitts and Nevis", flagEmoji: "🇰🇳", region: "Americas" },
  { code: "LC", code3: "LCA", name: "Saint Lucia", flagEmoji: "🇱🇨", region: "Americas" },
  { code: "VC", code3: "VCT", name: "Saint Vincent and the Grenadines", flagEmoji: "🇻🇨", region: "Americas" },
  { code: "WS", code3: "WSM", name: "Samoa", flagEmoji: "🇼🇸", region: "Oceania" },
  { code: "SM", code3: "SMR", name: "San Marino", flagEmoji: "🇸🇲", region: "Europe" },
  { code: "ST", code3: "STP", name: "Sao Tome and Principe", flagEmoji: "🇸🇹", region: "Africa" },
  { code: "SA", code3: "SAU", name: "Saudi Arabia", flagEmoji: "🇸🇦", region: "Asia" },
  { code: "SN", code3: "SEN", name: "Senegal", flagEmoji: "🇸🇳", region: "Africa" },
  { code: "RS", code3: "SRB", name: "Serbia", flagEmoji: "🇷🇸", region: "Europe" },
  { code: "SC", code3: "SYC", name: "Seychelles", flagEmoji: "🇸🇨", region: "Africa" },
  { code: "SL", code3: "SLE", name: "Sierra Leone", flagEmoji: "🇸🇱", region: "Africa" },
  { code: "SG", code3: "SGP", name: "Singapore", flagEmoji: "🇸🇬", region: "Asia" },
  { code: "SK", code3: "SVK", name: "Slovakia", flagEmoji: "🇸🇰", region: "Europe" },
  { code: "SI", code3: "SVN", name: "Slovenia", flagEmoji: "🇸🇮", region: "Europe" },
  { code: "SB", code3: "SLB", name: "Solomon Islands", flagEmoji: "🇸🇧", region: "Oceania" },
  { code: "SO", code3: "SOM", name: "Somalia", flagEmoji: "🇸🇴", region: "Africa" },
  { code: "ZA", code3: "ZAF", name: "South Africa", flagEmoji: "🇿🇦", region: "Africa" },
  { code: "SS", code3: "SSD", name: "South Sudan", flagEmoji: "🇸🇸", region: "Africa" },
  { code: "ES", code3: "ESP", name: "Spain", flagEmoji: "🇪🇸", region: "Europe" },
  { code: "LK", code3: "LKA", name: "Sri Lanka", flagEmoji: "🇱🇰", region: "Asia" },
  { code: "SD", code3: "SDN", name: "Sudan", flagEmoji: "🇸🇩", region: "Africa" },
  { code: "SR", code3: "SUR", name: "Suriname", flagEmoji: "🇸🇷", region: "Americas" },
  { code: "SE", code3: "SWE", name: "Sweden", flagEmoji: "🇸🇪", region: "Europe" },
  { code: "CH", code3: "CHE", name: "Switzerland", flagEmoji: "🇨🇭", region: "Europe" },
  { code: "SY", code3: "SYR", name: "Syria", flagEmoji: "🇸🇾", region: "Asia" },
  { code: "TW", code3: "TWN", name: "Taiwan", flagEmoji: "🇹🇼", region: "Asia" },
  { code: "TJ", code3: "TJK", name: "Tajikistan", flagEmoji: "🇹🇯", region: "Asia" },
  { code: "TZ", code3: "TZA", name: "Tanzania", flagEmoji: "🇹🇿", region: "Africa" },
  { code: "TH", code3: "THA", name: "Thailand", flagEmoji: "🇹🇭", region: "Asia" },
  { code: "TL", code3: "TLS", name: "Timor-Leste", flagEmoji: "🇹🇱", region: "Asia" },
  { code: "TG", code3: "TGO", name: "Togo", flagEmoji: "🇹🇬", region: "Africa" },
  { code: "TO", code3: "TON", name: "Tonga", flagEmoji: "🇹🇴", region: "Oceania" },
  { code: "TT", code3: "TTO", name: "Trinidad and Tobago", flagEmoji: "🇹🇹", region: "Americas" },
  { code: "TN", code3: "TUN", name: "Tunisia", flagEmoji: "🇹🇳", region: "Africa" },
  { code: "TR", code3: "TUR", name: "Turkey", flagEmoji: "🇹🇷", region: "Asia" },
  { code: "TM", code3: "TKM", name: "Turkmenistan", flagEmoji: "🇹🇲", region: "Asia" },
  { code: "TV", code3: "TUV", name: "Tuvalu", flagEmoji: "🇹🇻", region: "Oceania" },
  { code: "UG", code3: "UGA", name: "Uganda", flagEmoji: "🇺🇬", region: "Africa" },
  { code: "UA", code3: "UKR", name: "Ukraine", flagEmoji: "🇺🇦", region: "Europe" },
  { code: "AE", code3: "ARE", name: "United Arab Emirates", flagEmoji: "🇦🇪", region: "Asia" },
  { code: "GB", code3: "GBR", name: "United Kingdom", flagEmoji: "🇬🇧", region: "Europe" },
  { code: "US", code3: "USA", name: "United States", flagEmoji: "🇺🇸", region: "Americas" },
  { code: "UY", code3: "URY", name: "Uruguay", flagEmoji: "🇺🇾", region: "Americas" },
  { code: "UZ", code3: "UZB", name: "Uzbekistan", flagEmoji: "🇺🇿", region: "Asia" },
  { code: "VU", code3: "VUT", name: "Vanuatu", flagEmoji: "🇻🇺", region: "Oceania" },
  { code: "VE", code3: "VEN", name: "Venezuela", flagEmoji: "🇻🇪", region: "Americas" },
  { code: "VN", code3: "VNM", name: "Vietnam", flagEmoji: "🇻🇳", region: "Asia" },
  { code: "YE", code3: "YEM", name: "Yemen", flagEmoji: "🇾🇪", region: "Asia" },
  { code: "ZM", code3: "ZMB", name: "Zambia", flagEmoji: "🇿🇲", region: "Africa" },
  { code: "ZW", code3: "ZWE", name: "Zimbabwe", flagEmoji: "🇿🇼", region: "Africa" },
];

const seededSimInventory = [
  { imsi: "641200029999500", iccid: "89256201000000020114" },
  { imsi: "641200029999501", iccid: "89256201000000020122" },
  { imsi: "641200029999502", iccid: "89256201000000020130" },
  { imsi: "641200029999503", iccid: "89256201000000020148" },
  { imsi: "641200029999504", iccid: "89256201000000020155" },
  { imsi: "641200029999505", iccid: "89256201000000020163" },
  { imsi: "641200029999506", iccid: "89256201000000020171" },
  { imsi: "641200029999507", iccid: "89256201000000020189" },
  { imsi: "641200029999508", iccid: "89256201000000020197" },
  { imsi: "641200029999509", iccid: "89256201000000020205" },
  { imsi: "641200029999510", iccid: "89256201000000020213" },
  { imsi: "641200029999511", iccid: "89256201000000020221" },
];

async function main() {
  // Nationalities
  await prisma.nationality.createMany({
    data: nationalities,
    skipDuplicates: true,
  });
  console.log(`Seeded ${nationalities.length} nationalities`);

  // SIM inventory (eSIM)
  const simData = seededSimInventory.map((s) => ({
    ...s,
    type: "esim",
    category: "tourist",
    batchId: "iplook-emrg-launch-01",
    status: "available" as const,
  }));
  await prisma.simInventory.createMany({ data: simData, skipDuplicates: true });
  console.log(`Seeded ${simData.length} SIM inventory rows`);

  // MSISDN pool
  const msisdnData: { msisdn: string; category: string; status: "available" }[] = [];
  for (let i = 0; i <= 20; i++) {
    msisdnData.push({
      msisdn: `2567240300${i.toString().padStart(2, "0")}`,
      category: "tourist",
      status: "available",
    });
  }
  await prisma.msisdnPool.createMany({ data: msisdnData, skipDuplicates: true });
  console.log(`Seeded ${msisdnData.length} MSISDN pool rows`);

  // Default admin user
  const passwordHash = await bcrypt.hash("Admin@KYC2026", 10);
  await prisma.user.upsert({
    where: { email: "admin@hamiltel.ug" },
    update: {},
    create: {
      email: "admin@hamiltel.ug",
      passwordHash,
      name: "KYC Admin",
      role: "admin",
    },
  });
  console.log("Seeded default admin user: admin@hamiltel.ug / Admin@KYC2026");
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
